### ISSUE TITLE
Add copy right information to LICENSE file

### ISSUE THREAD

**Issue by stevenlius** [BarclaysAfrica/helloworld#1]
License file missing copyright information- Line 189

**Comment by coppermann** [comment]
I think the copyright information should not be added to the License appendix, 
but instead at the top of each the code file.

This is based on [http://www.apache.org/legal/src-headers.html], heading [DOES THIS POLICY APPLY TO PROJECTS OUTSIDE THE ASF THAT USE THE APACHE LICENSE?]
and [http://www.apache.org/licenses/LICENSE-2.0.html#apply].

The copyright thus replaces the default apache license notice added to the top of ASF code files,
as outlined in heading [SOURCE FILE HEADERS FOR CODE DEVELOPED AT THE ASF] of [http://www.apache.org/legal/src-headers.html]

**Comment by potgieterdl** [comment]
Thanks for spotting this, i`ll update and add.
